In [2]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.11.0+cu128
CUDA available: True


In [3]:
x = torch.tensor([1,2,3,4,5])
print(x)
print(type(x))
print("Tensor : ",x.shape)
print("Number of dimemsions:",x.ndim)
print("Number of Elements :",x.numel())

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
Tensor :  torch.Size([5])
Number of dimemsions: 1
Number of Elements : 5


In [4]:
X = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(X)
print("Shape:", X.shape)
print("Dimensions:", X.ndim)
print("Elements:", X.numel())

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Dimensions: 2
Elements: 6


In [5]:
print(X)
print("dtype:", X.dtype)
X_float = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

print(X_float)
print("dtype:", X_float.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
dtype: torch.int64
tensor([[1., 2., 3.],
        [4., 5., 6.]])
dtype: torch.float32


In [6]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([0.2500, 0.4000, 0.5000])


In [7]:
A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

C = A @ B

print(C)

tensor([[19., 22.],
        [43., 50.]])


In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

a_gpu = a.to(device)

print("Device:", a_gpu.device)
print(torch.cuda.get_device_name(0))

Device: cuda:0
NVIDIA GeForce RTX 3050 Laptop GPU


In [11]:
x = torch.tensor(2.0, requires_grad=True)

print(x)
print(x.requires_grad)

tensor(2., requires_grad=True)
True


In [12]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()

print("x:", x)
print("y:", y)
print("Gradient:", x.grad)

x: tensor(2., requires_grad=True)
y: tensor(4., grad_fn=<PowBackward0>)
Gradient: tensor(4.)


In [13]:
w = torch.tensor(2.0, requires_grad=True)

loss = (w - 5) ** 2

loss.backward()

print("w:", w)
print("Loss:", loss)
print("Gradient:", w.grad)

w: tensor(2., requires_grad=True)
Loss: tensor(9., grad_fn=<PowBackward0>)
Gradient: tensor(-6.)


In [14]:
w = torch.tensor(2.0, requires_grad=True)

learning_rate = 0.1

for step in range(10):
    loss = (w - 5) ** 2

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad

    w.grad.zero_()

    print(
        "Step:", step + 1,
        "w:", w.item(),
        "Loss:", loss.item()
    )

Step: 1 w: 2.5999999046325684 Loss: 9.0
Step: 2 w: 3.0799999237060547 Loss: 5.760000228881836
Step: 3 w: 3.4639999866485596 Loss: 3.6864001750946045
Step: 4 w: 3.771199941635132 Loss: 2.3592960834503174
Step: 5 w: 4.016960144042969 Loss: 1.5099495649337769
Step: 6 w: 4.213568210601807 Loss: 0.9663673639297485
Step: 7 w: 4.370854377746582 Loss: 0.6184749603271484
Step: 8 w: 4.496683597564697 Loss: 0.39582422375679016
Step: 9 w: 4.597346782684326 Loss: 0.2533273994922638
Step: 10 w: 4.677877426147461 Loss: 0.16212961077690125
