In [2]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.11.0+cu128
CUDA available: True


In [4]:
x = torch.tensor([1,2,3,4,5])
print(x)
print(type(x))
print("Tensor : ",x.shape)
print("Number of dimemsions:",x.ndim)
print("Number of Elements :",x.numel())

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
Tensor :  torch.Size([5])
Number of dimemsions: 1
Number of Elements : 5


In [5]:
X = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(X)
print("Shape:", X.shape)
print("Dimensions:", X.ndim)
print("Elements:", X.numel())

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Dimensions: 2
Elements: 6


In [7]:
print(X)
print("dtype:", X.dtype)
X_float = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

print(X_float)
print("dtype:", X_float.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
dtype: torch.int64
tensor([[1., 2., 3.],
        [4., 5., 6.]])
dtype: torch.float32
